-- 3.15.1 Global taxonomy for Israel Reference Catalog v1.
-- These rows are identities and physical measurement vocabulary only. They do
-- not assert prices, productivity, labor rates, or operation time.

insert into public.reference_material_categories (
    category_code, category_name, department, parent_category_code, sort_order
) values
    ('wood_sheet', 'Wood sheet materials', 'wood', null, 100),
    ('solid_wood', 'Solid wood', 'wood', null, 200),
    ('wood_surface', 'Wood surfaces and edges', 'wood', null, 300),
    ('metal_sheet', 'Sheet metal', 'metal', null, 400),
    ('metal_profile', 'Metal profiles and sections', 'metal', null, 500),
    ('glass_mirror', 'Glass and mirror', 'glass_stone_plastic', null, 600),
    ('stone_slab', 'Stone and slab products', 'glass_stone_plastic', null, 700),
    ('plastic_sheet', 'Plastic sheet', 'glass_stone_plastic', null, 800),
    ('furniture_hardware', 'Furniture hardware', 'hardware', null, 900),
    ('fastener', 'Fasteners and connectors', 'hardware', null, 1000),
    ('wood_coating', 'Wood coatings', 'coating', null, 1100),
    ('metal_coating', 'Metal coatings', 'coating', null, 1200),
    ('adhesive_sealant', 'Adhesives and sealants', 'consumable', null, 1300),
    ('abrasive', 'Abrasives', 'consumable', null, 1400),
    ('welding_consumable', 'Welding consumables', 'consumable', null, 1500),
    ('shop_consumable', 'General shop consumables', 'consumable', null, 1600),
    ('packaging_material', 'Packaging materials', 'packaging', null, 1700),
    ('mdf', 'MDF', 'wood', 'wood_sheet', 110),
    ('particleboard', 'Particleboard', 'wood', 'wood_sheet', 120),
    ('plywood', 'Plywood', 'wood', 'wood_sheet', 130),
    ('hardboard', 'Hardboard and backing board', 'wood', 'wood_sheet', 140),
    ('osb', 'Oriented strand board', 'wood', 'wood_sheet', 145),
    ('compact_laminate', 'Compact laminate', 'wood', 'wood_sheet', 150),
    ('softwood', 'Softwood', 'wood', 'solid_wood', 210),
    ('hardwood', 'Hardwood', 'wood', 'solid_wood', 220),
    ('glued_wood_panel', 'Glued wood panel', 'wood', 'solid_wood', 230),
    ('veneer', 'Veneer', 'wood', 'wood_surface', 310),
    ('decorative_laminate', 'Decorative laminate', 'wood', 'wood_surface', 320),
    ('edge_band', 'Edge band', 'wood', 'wood_surface', 330),
    ('carbon_steel_sheet', 'Carbon steel sheet', 'metal', 'metal_sheet', 410),
    ('galvanized_steel_sheet', 'Galvanized steel sheet', 'metal', 'metal_sheet', 420),
    ('stainless_steel_sheet', 'Stainless steel sheet', 'metal', 'metal_sheet', 430),
    ('aluminium_sheet', 'Aluminium sheet', 'metal', 'metal_sheet', 440),
    ('steel_tube', 'Steel tube', 'metal', 'metal_profile', 510),
    ('steel_section', 'Steel section', 'metal', 'metal_profile', 520),
    ('steel_bar', 'Steel bar and flat', 'metal', 'metal_profile', 530),
    ('aluminium_profile', 'Aluminium profile', 'metal', 'metal_profile', 540),
    ('float_glass', 'Float glass', 'glass_stone_plastic', 'glass_mirror', 610),
    ('tempered_glass', 'Tempered glass', 'glass_stone_plastic', 'glass_mirror', 620),
    ('laminated_glass', 'Laminated glass', 'glass_stone_plastic', 'glass_mirror', 630),
    ('mirror', 'Mirror', 'glass_stone_plastic', 'glass_mirror', 640),
    ('engineered_quartz', 'Engineered quartz', 'glass_stone_plastic', 'stone_slab', 710),
    ('natural_stone', 'Natural stone', 'glass_stone_plastic', 'stone_slab', 720),
    ('porcelain_slab', 'Porcelain slab', 'glass_stone_plastic', 'stone_slab', 730),
    ('acrylic_sheet', 'Acrylic sheet', 'glass_stone_plastic', 'plastic_sheet', 810),
    ('polycarbonate_sheet', 'Polycarbonate sheet', 'glass_stone_plastic', 'plastic_sheet', 820),
    ('pvc_sheet', 'PVC sheet', 'glass_stone_plastic', 'plastic_sheet', 830),
    ('hinge', 'Hinges', 'hardware', 'furniture_hardware', 910),
    ('drawer_runner', 'Drawer runners', 'hardware', 'furniture_hardware', 920),
    ('drawer_system', 'Drawer systems', 'hardware', 'furniture_hardware', 930),
    ('lift_system', 'Lift systems', 'hardware', 'furniture_hardware', 940),
    ('handle', 'Handles and pulls', 'hardware', 'furniture_hardware', 950),
    ('lock_latch', 'Locks and latches', 'hardware', 'furniture_hardware', 960),
    ('leg_caster', 'Legs and casters', 'hardware', 'furniture_hardware', 970),
    ('mounting_hardware', 'Mounting hardware', 'hardware', 'furniture_hardware', 980),
    ('screw_bolt', 'Screws and bolts', 'hardware', 'fastener', 1010),
    ('dowel_confirmat', 'Dowels and confirmats', 'hardware', 'fastener', 1020),
    ('anchor', 'Anchors', 'hardware', 'fastener', 1030),
    ('wood_primer', 'Wood primer and sealer', 'coating', 'wood_coating', 1110),
    ('wood_stain', 'Wood stain', 'coating', 'wood_coating', 1120),
    ('wood_lacquer', 'Wood lacquer', 'coating', 'wood_coating', 1130),
    ('wood_paint', 'Wood paint', 'coating', 'wood_coating', 1140),
    ('metal_primer', 'Metal primer', 'coating', 'metal_coating', 1210),
    ('metal_paint', 'Metal paint', 'coating', 'metal_coating', 1220),
    ('powder_coating_material', 'Powder coating material', 'coating', 'metal_coating', 1230),
    ('wood_adhesive', 'Wood adhesive', 'consumable', 'adhesive_sealant', 1310),
    ('contact_adhesive', 'Contact adhesive', 'consumable', 'adhesive_sealant', 1320),
    ('construction_adhesive', 'Construction adhesive', 'consumable', 'adhesive_sealant', 1330),
    ('sealant', 'Sealant', 'consumable', 'adhesive_sealant', 1340),
    ('sandpaper_disc', 'Sanding discs', 'consumable', 'abrasive', 1410),
    ('sandpaper_roll_sheet', 'Sanding rolls and hand sheets', 'consumable', 'abrasive', 1415),
    ('abrasive_belt', 'Abrasive belts', 'consumable', 'abrasive', 1420),
    ('welding_wire_rod', 'Welding wire and rods', 'consumable', 'welding_consumable', 1510),
    ('shielding_gas', 'Shielding gas', 'consumable', 'welding_consumable', 1520),
    ('masking_material', 'Masking materials', 'consumable', 'shop_consumable', 1610),
    ('paint_thinner_solvent', 'Paint thinners and cleaning solvents', 'consumable', 'shop_consumable', 1620),
    ('solvent_cleaner', 'Solvents and cleaners', 'consumable', 'shop_consumable', 1620),
    ('cardboard', 'Cardboard', 'packaging', 'packaging_material', 1710),
    ('protective_foam', 'Protective foam', 'packaging', 'packaging_material', 1720),
    ('stretch_wrap', 'Stretch wrap', 'packaging', 'packaging_material', 1730),
    ('edge_protector', 'Edge protectors', 'packaging', 'packaging_material', 1740),
    ('pallet', 'Pallets', 'packaging', 'packaging_material', 1750)
on conflict (category_code) do update set
    category_name = excluded.category_name,
    department = excluded.department,
    parent_category_code = excluded.parent_category_code,
    sort_order = excluded.sort_order,
    active = true;

insert into public.reference_labor_roles (
    role_code, role_name, department, company_position_code, company_match_policy
) values
    ('owner_director', 'Owner / Director', 'general', 'owner_director', 'exact'),
    ('general_manager', 'General Manager', 'general', 'general_manager', 'exact'),
    ('project_manager', 'Project Manager', 'general', 'project_manager', 'exact'),
    ('production_manager', 'Production Manager', 'general', 'production_manager', 'exact'),
    ('accountant', 'Accountant', 'general', 'accountant', 'exact'),
    ('office_administrator', 'Office Administrator', 'general', 'office_administrator', 'exact'),
    ('estimator', 'Estimator', 'general', 'estimator', 'exact'),
    ('sales_manager', 'Sales Manager', 'general', 'sales_manager', 'exact'),
    ('designer_draftsperson', 'Designer', 'general', 'designer_draftsperson', 'exact'),
    ('carpenter', 'Carpenter', 'wood', 'carpenter', 'exact'),
    ('welder', 'Welder', 'metal', 'welder', 'exact'),
    ('cnc_operator', 'CNC Operator', 'general', 'cnc_operator', 'exact'),
    ('painter_finisher', 'Painter', 'coating', 'painter_finisher', 'exact'),
    ('installer', 'Installer', 'installation', 'installer', 'exact'),
    ('general_worker', 'Worker', 'general', 'general_worker', 'exact'),
    ('wood_machine_operator', 'Wood Machine Operator', 'wood', 'carpenter', 'requires_confirmation'),
    ('metal_machine_operator', 'Metal Machine Operator', 'metal', 'welder', 'requires_confirmation'),
    ('sheet_laser_operator', 'Sheet Laser Operator', 'metal', 'cnc_operator', 'requires_confirmation'),
    ('press_brake_operator', 'Press Brake Operator', 'metal', 'welder', 'requires_confirmation'),
    ('grinder_polisher', 'Grinder / Polisher', 'metal', 'general_worker', 'requires_confirmation'),
    ('glass_fabricator', 'Glass Fabricator', 'general', null, 'none'),
    ('stone_fabricator', 'Stone Fabricator', 'general', null, 'none'),
    ('plastic_fabricator', 'Plastic Fabricator', 'general', null, 'none'),
    ('powder_coating_operator', 'Powder Coating Operator', 'coating', 'painter_finisher', 'requires_confirmation'),
    ('sandblasting_operator', 'Sandblasting Operator', 'coating', 'painter_finisher', 'requires_confirmation'),
    ('galvanizing_operator', 'Galvanizing Operator', 'coating', null, 'none'),
    ('packer', 'Packer', 'general', 'general_worker', 'requires_confirmation'),
    ('delivery_driver', 'Delivery Driver', 'general', 'general_worker', 'requires_confirmation'),
    ('low_voltage_installer', 'Low-voltage Installer', 'installation', 'installer', 'requires_confirmation')
on conflict (role_code) do update set
    role_name = excluded.role_name,
    department = excluded.department,
    company_position_code = excluded.company_position_code,
    company_match_policy = excluded.company_match_policy,
    active = true;

insert into public.reference_operation_drivers (
    driver_code, driver_name, unit, quantity_type, description, sort_order
) values
    ('batch_count', 'Batch count', 'batch', 'count', 'Separate production or colour batches.', 10),
    ('object_count', 'Object count', 'object', 'count', 'Distinct estimated objects.', 20),
    ('sheet_count', 'Sheet count', 'sheet', 'count', 'Sheets handled or processed.', 30),
    ('part_count', 'Part count', 'part', 'count', 'Individual fabricated parts.', 40),
    ('cut_count', 'Cut count', 'cut', 'count', 'Individual cutting actions.', 50),
    ('cut_length_lm', 'Cut length', 'lm', 'length', 'Total cutting path length.', 60),
    ('edge_length_lm', 'Edge length', 'lm', 'length', 'Total processed edge length.', 70),
    ('profile_length_lm', 'Profile length', 'lm', 'length', 'Total routed or formed profile length.', 80),
    ('surface_area_sqm', 'Surface area', 'sqm', 'area', 'Total relevant surface area.', 90),
    ('finish_area_sqm', 'Finish area', 'sqm', 'area', 'Area receiving the specified finish system.', 100),
    ('material_length_lm', 'Material length', 'lm', 'length', 'Linear material length handled or processed.', 110),
    ('material_area_sqm', 'Material area', 'sqm', 'area', 'Sheet or slab material area.', 120),
    ('material_weight_kg', 'Material weight', 'kg', 'weight', 'Material weight handled or processed.', 130),
    ('material_volume_cbm', 'Material volume', 'cbm', 'volume', 'Material volume handled or processed.', 140),
    ('hole_count', 'Hole count', 'hole', 'count', 'Drilled, bored, punched, or cut holes.', 150),
    ('groove_length_lm', 'Groove length', 'lm', 'length', 'Total groove or dado length.', 160),
    ('pocket_count', 'Pocket count', 'pocket', 'count', 'Machined pockets or recesses.', 170),
    ('cutout_count', 'Cutout count', 'cutout', 'count', 'Internal or perimeter cutouts.', 180),
    ('tool_change_count', 'Tool change count', 'change', 'count', 'Required tool changes within a production run.', 190),
    ('bend_count', 'Bend count', 'bend', 'count', 'Sheet or profile bends.', 200),
    ('joint_count', 'Joint count', 'joint', 'count', 'Welded, glued, or mechanically assembled joints.', 210),
    ('weld_length_lm', 'Weld length', 'lm', 'length', 'Total weld length.', 220),
    ('grind_length_lm', 'Grinding length', 'lm', 'length', 'Total weld or edge grinding length.', 230),
    ('seam_length_lm', 'Seam length', 'lm', 'length', 'Total joined seam length.', 240),
    ('glueup_count', 'Glue-up count', 'glueup', 'count', 'Separate glue-up assemblies.', 250),
    ('glueup_area_sqm', 'Glue-up area', 'sqm', 'area', 'Finished area of glued panels or laminations.', 260),
    ('cabinet_count', 'Cabinet count', 'cabinet', 'count', 'Cabinet carcasses assembled or installed.', 270),
    ('drawer_count', 'Drawer count', 'drawer', 'count', 'Drawer boxes or systems assembled or installed.', 280),
    ('door_front_count', 'Door or front count', 'front', 'count', 'Doors and visible fronts handled.', 290),
    ('hardware_count', 'Hardware count', 'ea', 'count', 'Individual hardware items installed.', 300),
    ('anchor_count', 'Anchor count', 'anchor', 'count', 'Wall, floor, or ceiling anchors installed.', 310),
    ('electrical_point_count', 'Electrical point count', 'point', 'count', 'Low-voltage connections, drivers, or test points.', 320),
    ('cable_length_lm', 'Cable length', 'lm', 'length', 'Total cable routing length.', 330),
    ('led_length_lm', 'LED length', 'lm', 'length', 'Total LED strip or profile length.', 340),
    ('package_count', 'Package count', 'package', 'count', 'Packages prepared or handled.', 350),
    ('trip_count', 'Trip count', 'trip', 'count', 'Delivery or service trips.', 360),
    ('site_visit_count', 'Site visit count', 'visit', 'count', 'Measurement, installation, or service visits.', 370),
    ('floor_count', 'Floor count', 'floor', 'count', 'Floors relevant to manual carrying.', 380),
    ('drawing_page_count', 'Drawing page count', 'page', 'count', 'Drawing pages reviewed or produced.', 390),
    ('revision_count', 'Revision count', 'revision', 'count', 'Documented design or production revisions.', 400),
    ('supplier_quote_count', 'Supplier quote count', 'quote', 'count', 'Supplier quote requests handled.', 410),
    ('subcontract_item_count', 'Subcontract item count', 'item', 'count', 'Distinct outsourced line items.', 420),
    ('defect_count', 'Defect count', 'defect', 'count', 'Documented repair or touch-up points.', 430)
on conflict (driver_code) do update set
    driver_name = excluded.driver_name,
    unit = excluded.unit,
    quantity_type = excluded.quantity_type,
    description = excluded.description,
    sort_order = excluded.sort_order,
    active = true;

insert into public.reference_operations (
    operation_code, department, operation_name, description
) values
    ('site_measurement', 'preproduction', 'Site measurement', 'Measure and document site conditions relevant to production.'),
    ('estimate_review', 'preproduction', 'Estimate review', 'Review scope, quantities, exclusions, and unresolved evidence.'),
    ('shop_drawing', 'preproduction', 'Shop drawing', 'Prepare fabrication-ready drawings and schedules.'),
    ('cnc_programming', 'preproduction', 'CNC programming', 'Prepare machine programs, tooling, and machining sequence.'),
    ('sheet_nesting', 'preproduction', 'Sheet nesting', 'Arrange parts on sheet stock and verify yield and grain constraints.'),
    ('supplier_quotation', 'preproduction', 'Supplier quotation', 'Prepare and review an external material or service quotation request.'),
    ('quality_inspection', 'preproduction', 'Quality inspection', 'Inspect fabricated work against documented requirements.'),
    ('panel_material_handling', 'wood', 'Panel material handling', 'Move, stage, label, and sort panel stock and parts.'),
    ('panel_saw_cutting', 'wood', 'Panel saw cutting', 'Cut rectangular panel parts on a panel or table saw.'),
    ('cnc_router_profile_cutting', 'wood', 'CNC router profile cutting', 'Cut panel or wood part profiles on a CNC router.'),
    ('cnc_vertical_drilling', 'wood', 'CNC vertical drilling', 'Machine vertical holes on a CNC router.'),
    ('cnc_horizontal_drilling', 'wood', 'CNC horizontal drilling', 'Machine horizontal or end holes on supported equipment.'),
    ('cnc_grooving', 'wood', 'CNC grooving', 'Machine grooves, dados, and channels on a CNC router.'),
    ('cnc_pocketing', 'wood', 'CNC pocketing', 'Machine pockets and recesses on a CNC router.'),
    ('manual_panel_cutting', 'wood', 'Manual panel cutting', 'Perform supported straight low-volume cuts without CNC routing.'),
    ('manual_drilling', 'wood', 'Manual drilling', 'Drill supported low-volume holes with manual or stationary tools.'),
    ('manual_routing', 'wood', 'Manual routing', 'Route supported edges, grooves, or simple features manually.'),
    ('edge_banding', 'wood', 'Edge banding', 'Apply and trim edge band to panel parts.'),
    ('veneer_lamination', 'wood', 'Veneer or laminate pressing', 'Prepare and press veneer or laminate to a substrate.'),
    ('solid_wood_ripping', 'wood', 'Solid wood ripping', 'Rip solid wood stock to width.'),
    ('solid_wood_crosscutting', 'wood', 'Solid wood crosscutting', 'Crosscut solid wood stock to length.'),
    ('solid_wood_jointing_planing', 'wood', 'Solid wood jointing and planing', 'Joint and plane solid wood stock to final section.'),
    ('solid_wood_profiling', 'wood', 'Solid wood profiling', 'Machine moulded, curved, chamfered, or radiused profiles.'),
    ('solid_wood_glueup', 'wood', 'Solid wood glue-up', 'Prepare, glue, clamp, and release solid wood assemblies or panels.'),
    ('wood_sanding', 'wood', 'Wood sanding', 'Sand wood or panel surfaces and edges to the required preparation level.'),
    ('carcass_assembly', 'assembly', 'Carcass assembly', 'Assemble cabinet carcasses and internal divisions.'),
    ('drawer_assembly', 'assembly', 'Drawer assembly', 'Assemble drawer boxes and drawer systems.'),
    ('door_front_fitting', 'assembly', 'Door and front fitting', 'Fit and adjust doors, drawer fronts, and related hardware.'),
    ('hardware_installation', 'assembly', 'Hardware installation', 'Install hinges, runners, handles, connectors, and mechanisms.'),
    ('workshop_dry_fit', 'assembly', 'Workshop dry fit', 'Trial-assemble and adjust work before finishing or delivery.'),
    ('sheet_laser_cutting', 'metal', 'Sheet laser cutting', 'Laser-cut sheet metal parts.'),
    ('sheet_shearing', 'metal', 'Sheet shearing', 'Cut supported straight sheet-metal parts by shear or guillotine.'),
    ('metal_profile_cutting', 'metal', 'Metal profile cutting', 'Cut tubes, bars, and structural profiles to length.'),
    ('metal_drilling', 'metal', 'Metal drilling', 'Drill holes in metal parts or assemblies.'),
    ('metal_punching', 'metal', 'Metal punching', 'Punch holes or features in sheet metal.'),
    ('sheet_metal_bending', 'metal', 'Sheet metal bending', 'Form sheet-metal bends on a press brake.'),
    ('metal_profile_bending', 'metal', 'Metal profile bending', 'Bend tube or profile sections.'),
    ('metal_rolling', 'metal', 'Metal rolling', 'Roll sheet or profile material to radius.'),
    ('mig_mag_welding', 'metal', 'MIG or MAG welding', 'Join metal components using MIG or MAG welding.'),
    ('tig_welding', 'metal', 'TIG welding', 'Join metal components using TIG welding.'),
    ('metal_grinding', 'metal', 'Metal grinding', 'Grind welds, edges, and surface defects.'),
    ('metal_polishing', 'metal', 'Metal polishing', 'Polish exposed metal surfaces to the specified finish.'),
    ('metal_assembly', 'metal', 'Metal assembly', 'Fit and mechanically assemble metal parts.'),
    ('glass_cutting', 'glass_stone_plastic', 'Glass cutting', 'Cut non-tempered glass or mirror to supported geometry.'),
    ('glass_edge_processing', 'glass_stone_plastic', 'Glass edge processing', 'Grind, polish, or bevel glass and mirror edges.'),
    ('glass_drilling', 'glass_stone_plastic', 'Glass drilling', 'Drill supported holes in glass before tempering.'),
    ('glass_tempering', 'glass_stone_plastic', 'Glass tempering', 'Heat-treat prepared glass through an external or in-house process.'),
    ('stone_cutting', 'glass_stone_plastic', 'Stone cutting', 'Cut stone, quartz, or porcelain slab parts.'),
    ('stone_edge_processing', 'glass_stone_plastic', 'Stone edge processing', 'Machine and polish specified slab edges.'),
    ('stone_cutout', 'glass_stone_plastic', 'Stone cutout', 'Produce sink, cooktop, or technical slab cutouts.'),
    ('stone_seaming', 'glass_stone_plastic', 'Stone seaming', 'Prepare, join, and finish slab seams.'),
    ('acrylic_cnc_machining', 'glass_stone_plastic', 'Acrylic CNC machining', 'CNC-cut, drill, groove, or pocket acrylic parts.'),
    ('acrylic_laser_cutting', 'glass_stone_plastic', 'Acrylic laser cutting', 'Laser-cut supported acrylic parts.'),
    ('acrylic_thermoforming', 'glass_stone_plastic', 'Acrylic thermoforming', 'Heat and form acrylic over a prepared form.'),
    ('finish_surface_preparation', 'coating', 'Finish surface preparation', 'Clean, fill, mask, and prepare surfaces for finishing.'),
    ('wood_staining', 'coating', 'Wood staining', 'Apply and equalize stain on prepared wood.'),
    ('wood_priming', 'coating', 'Wood priming', 'Apply wood primer or sealer and prepare between coats.'),
    ('wood_lacquering', 'coating', 'Wood lacquering', 'Apply the specified lacquer system to prepared wood.'),
    ('wet_spray_painting', 'coating', 'Wet spray painting', 'Apply liquid paint by spray to prepared components.'),
    ('powder_coating_preparation', 'coating', 'Powder coating preparation', 'Prepare and rack metal parts for powder coating.'),
    ('powder_coating_application', 'coating', 'Powder coating application', 'Apply and cure powder coating.'),
    ('sandblasting', 'coating', 'Sandblasting', 'Blast-clean or texture supported parts.'),
    ('galvanizing', 'coating', 'Galvanizing', 'Apply a galvanized protective finish through the selected route.'),
    ('protective_packaging', 'packaging', 'Protective packaging', 'Wrap, protect, label, and prepare fabricated items for transport.'),
    ('vehicle_loading', 'logistics', 'Vehicle loading', 'Load and secure packaged work for transport.'),
    ('delivery_trip', 'logistics', 'Delivery trip', 'Transport work to the specified destination.'),
    ('manual_site_carry', 'logistics', 'Manual site carry', 'Carry components from unloading point to installation area.'),
    ('site_protection', 'installation', 'Site protection', 'Protect relevant floors, walls, and adjacent work before installation.'),
    ('cabinet_installation', 'installation', 'Cabinet installation', 'Position, level, connect, and secure cabinet units.'),
    ('countertop_installation', 'installation', 'Countertop installation', 'Position, join, secure, and seal countertop components.'),
    ('metalwork_installation', 'installation', 'Metalwork installation', 'Position and secure fabricated metalwork.'),
    ('glass_mirror_installation', 'installation', 'Glass and mirror installation', 'Position and secure glass or mirror components.'),
    ('site_anchoring', 'installation', 'Site anchoring', 'Drill and install documented wall, floor, or ceiling anchors.'),
    ('site_sealing', 'installation', 'Site sealing', 'Apply sealant to installed joints and interfaces.'),
    ('led_low_voltage_installation', 'installation', 'LED and low-voltage installation', 'Fit supported LED profiles, strips, drivers, and low-voltage connections.'),
    ('final_adjustment', 'installation', 'Final adjustment', 'Align, adjust, test, and document installed components.'),
    ('site_cleanup', 'installation', 'Site cleanup', 'Remove installation debris and temporary protection within scope.')
on conflict (operation_code) do update set
    department = excluded.department,
    operation_name = excluded.operation_name,
    description = excluded.description,
    active = true,
    updated_at = now();

insert into public.reference_operation_roles (
    operation_id, role_code, capability_level
)
select o.operation_id, mapping.role_code, mapping.capability_level
from (values
    ('site_measurement', 'project_manager', 'primary'),
    ('site_measurement', 'installer', 'qualified'),
    ('estimate_review', 'estimator', 'primary'),
    ('shop_drawing', 'designer_draftsperson', 'primary'),
    ('cnc_programming', 'cnc_operator', 'primary'),
    ('cnc_programming', 'designer_draftsperson', 'qualified'),
    ('sheet_nesting', 'cnc_operator', 'primary'),
    ('supplier_quotation', 'estimator', 'primary'),
    ('quality_inspection', 'production_manager', 'primary'),
    ('panel_material_handling', 'general_worker', 'primary'),
    ('panel_saw_cutting', 'wood_machine_operator', 'primary'),
    ('panel_saw_cutting', 'carpenter', 'qualified'),
    ('panel_saw_cutting', 'general_worker', 'assistant'),
    ('cnc_router_profile_cutting', 'cnc_operator', 'primary'),
    ('cnc_vertical_drilling', 'cnc_operator', 'primary'),
    ('cnc_horizontal_drilling', 'cnc_operator', 'primary'),
    ('cnc_grooving', 'cnc_operator', 'primary'),
    ('cnc_pocketing', 'cnc_operator', 'primary'),
    ('manual_panel_cutting', 'carpenter', 'primary'),
    ('manual_drilling', 'carpenter', 'primary'),
    ('manual_routing', 'carpenter', 'primary'),
    ('edge_banding', 'wood_machine_operator', 'primary'),
    ('edge_banding', 'carpenter', 'qualified'),
    ('veneer_lamination', 'carpenter', 'primary'),
    ('solid_wood_ripping', 'wood_machine_operator', 'primary'),
    ('solid_wood_crosscutting', 'wood_machine_operator', 'primary'),
    ('solid_wood_jointing_planing', 'wood_machine_operator', 'primary'),
    ('solid_wood_profiling', 'wood_machine_operator', 'primary'),
    ('solid_wood_glueup', 'carpenter', 'primary'),
    ('wood_sanding', 'carpenter', 'primary'),
    ('wood_sanding', 'general_worker', 'qualified'),
    ('carcass_assembly', 'carpenter', 'primary'),
    ('drawer_assembly', 'carpenter', 'primary'),
    ('door_front_fitting', 'carpenter', 'primary'),
    ('hardware_installation', 'carpenter', 'primary'),
    ('workshop_dry_fit', 'carpenter', 'primary'),
    ('sheet_laser_cutting', 'sheet_laser_operator', 'primary'),
    ('sheet_shearing', 'metal_machine_operator', 'primary'),
    ('metal_profile_cutting', 'metal_machine_operator', 'primary'),
    ('metal_drilling', 'metal_machine_operator', 'primary'),
    ('metal_punching', 'metal_machine_operator', 'primary'),
    ('sheet_metal_bending', 'press_brake_operator', 'primary'),
    ('metal_profile_bending', 'metal_machine_operator', 'primary'),
    ('metal_rolling', 'metal_machine_operator', 'primary'),
    ('mig_mag_welding', 'welder', 'primary'),
    ('tig_welding', 'welder', 'primary'),
    ('metal_grinding', 'grinder_polisher', 'primary'),
    ('metal_polishing', 'grinder_polisher', 'primary'),
    ('metal_assembly', 'welder', 'primary'),
    ('glass_cutting', 'glass_fabricator', 'primary'),
    ('glass_edge_processing', 'glass_fabricator', 'primary'),
    ('glass_drilling', 'glass_fabricator', 'primary'),
    ('glass_tempering', 'glass_fabricator', 'primary'),
    ('stone_cutting', 'stone_fabricator', 'primary'),
    ('stone_edge_processing', 'stone_fabricator', 'primary'),
    ('stone_cutout', 'stone_fabricator', 'primary'),
    ('stone_seaming', 'stone_fabricator', 'primary'),
    ('acrylic_cnc_machining', 'plastic_fabricator', 'primary'),
    ('acrylic_laser_cutting', 'plastic_fabricator', 'primary'),
    ('acrylic_thermoforming', 'plastic_fabricator', 'primary'),
    ('finish_surface_preparation', 'painter_finisher', 'primary'),
    ('finish_surface_preparation', 'general_worker', 'assistant'),
    ('wood_staining', 'painter_finisher', 'primary'),
    ('wood_priming', 'painter_finisher', 'primary'),
    ('wood_lacquering', 'painter_finisher', 'primary'),
    ('wet_spray_painting', 'painter_finisher', 'primary'),
    ('powder_coating_preparation', 'powder_coating_operator', 'primary'),
    ('powder_coating_application', 'powder_coating_operator', 'primary'),
    ('sandblasting', 'sandblasting_operator', 'primary'),
    ('galvanizing', 'galvanizing_operator', 'primary'),
    ('protective_packaging', 'packer', 'primary'),
    ('vehicle_loading', 'general_worker', 'primary'),
    ('delivery_trip', 'delivery_driver', 'primary'),
    ('manual_site_carry', 'general_worker', 'primary'),
    ('site_protection', 'installer', 'primary'),
    ('cabinet_installation', 'installer', 'primary'),
    ('cabinet_installation', 'carpenter', 'qualified'),
    ('countertop_installation', 'installer', 'primary'),
    ('metalwork_installation', 'installer', 'primary'),
    ('metalwork_installation', 'welder', 'qualified'),
    ('glass_mirror_installation', 'installer', 'primary'),
    ('site_anchoring', 'installer', 'primary'),
    ('site_sealing', 'installer', 'primary'),
    ('led_low_voltage_installation', 'low_voltage_installer', 'primary'),
    ('final_adjustment', 'installer', 'primary'),
    ('site_cleanup', 'general_worker', 'primary')
) as mapping(operation_code, role_code, capability_level)
join public.reference_operations o
    on o.operation_code = mapping.operation_code
on conflict (operation_id, role_code) do update set
    capability_level = excluded.capability_level;

insert into public.reference_operation_driver_options (
    operation_id, driver_code, driver_purpose
)
select o.operation_id, mapping.driver_code, mapping.driver_purpose
from (values
    ('site_measurement', 'site_visit_count', 'primary'),
    ('estimate_review', 'object_count', 'primary'),
    ('estimate_review', 'drawing_page_count', 'secondary'),
    ('shop_drawing', 'drawing_page_count', 'primary'),
    ('shop_drawing', 'revision_count', 'secondary'),
    ('cnc_programming', 'part_count', 'primary'),
    ('cnc_programming', 'tool_change_count', 'secondary'),
    ('sheet_nesting', 'sheet_count', 'primary'),
    ('sheet_nesting', 'part_count', 'secondary'),
    ('supplier_quotation', 'supplier_quote_count', 'primary'),
    ('quality_inspection', 'part_count', 'primary'),
    ('panel_material_handling', 'sheet_count', 'primary'),
    ('panel_material_handling', 'part_count', 'secondary'),
    ('panel_saw_cutting', 'cut_count', 'primary'),
    ('panel_saw_cutting', 'part_count', 'secondary'),
    ('cnc_router_profile_cutting', 'cut_length_lm', 'primary'),
    ('cnc_router_profile_cutting', 'part_count', 'secondary'),
    ('cnc_vertical_drilling', 'hole_count', 'primary'),
    ('cnc_horizontal_drilling', 'hole_count', 'primary'),
    ('cnc_grooving', 'groove_length_lm', 'primary'),
    ('cnc_pocketing', 'pocket_count', 'primary'),
    ('manual_panel_cutting', 'cut_count', 'primary'),
    ('manual_drilling', 'hole_count', 'primary'),
    ('manual_routing', 'profile_length_lm', 'primary'),
    ('edge_banding', 'edge_length_lm', 'primary'),
    ('veneer_lamination', 'surface_area_sqm', 'primary'),
    ('solid_wood_ripping', 'material_length_lm', 'primary'),
    ('solid_wood_crosscutting', 'cut_count', 'primary'),
    ('solid_wood_jointing_planing', 'material_length_lm', 'primary'),
    ('solid_wood_profiling', 'profile_length_lm', 'primary'),
    ('solid_wood_glueup', 'glueup_area_sqm', 'primary'),
    ('solid_wood_glueup', 'glueup_count', 'secondary'),
    ('wood_sanding', 'surface_area_sqm', 'primary'),
    ('carcass_assembly', 'cabinet_count', 'primary'),
    ('drawer_assembly', 'drawer_count', 'primary'),
    ('door_front_fitting', 'door_front_count', 'primary'),
    ('hardware_installation', 'hardware_count', 'primary'),
    ('workshop_dry_fit', 'object_count', 'primary'),
    ('sheet_laser_cutting', 'cut_length_lm', 'primary'),
    ('sheet_laser_cutting', 'part_count', 'secondary'),
    ('sheet_shearing', 'cut_count', 'primary'),
    ('metal_profile_cutting', 'cut_count', 'primary'),
    ('metal_drilling', 'hole_count', 'primary'),
    ('metal_punching', 'hole_count', 'primary'),
    ('sheet_metal_bending', 'bend_count', 'primary'),
    ('metal_profile_bending', 'bend_count', 'primary'),
    ('metal_rolling', 'part_count', 'primary'),
    ('mig_mag_welding', 'weld_length_lm', 'primary'),
    ('mig_mag_welding', 'joint_count', 'secondary'),
    ('tig_welding', 'weld_length_lm', 'primary'),
    ('tig_welding', 'joint_count', 'secondary'),
    ('metal_grinding', 'grind_length_lm', 'primary'),
    ('metal_polishing', 'surface_area_sqm', 'primary'),
    ('metal_assembly', 'joint_count', 'primary'),
    ('glass_cutting', 'cut_length_lm', 'primary'),
    ('glass_edge_processing', 'edge_length_lm', 'primary'),
    ('glass_drilling', 'hole_count', 'primary'),
    ('glass_tempering', 'material_area_sqm', 'primary'),
    ('stone_cutting', 'cut_length_lm', 'primary'),
    ('stone_edge_processing', 'edge_length_lm', 'primary'),
    ('stone_cutout', 'cutout_count', 'primary'),
    ('stone_seaming', 'seam_length_lm', 'primary'),
    ('acrylic_cnc_machining', 'cut_length_lm', 'primary'),
    ('acrylic_cnc_machining', 'hole_count', 'secondary'),
    ('acrylic_laser_cutting', 'cut_length_lm', 'primary'),
    ('acrylic_thermoforming', 'part_count', 'primary'),
    ('finish_surface_preparation', 'surface_area_sqm', 'primary'),
    ('wood_staining', 'finish_area_sqm', 'primary'),
    ('wood_priming', 'finish_area_sqm', 'primary'),
    ('wood_lacquering', 'finish_area_sqm', 'primary'),
    ('wet_spray_painting', 'finish_area_sqm', 'primary'),
    ('powder_coating_preparation', 'finish_area_sqm', 'primary'),
    ('powder_coating_application', 'finish_area_sqm', 'primary'),
    ('sandblasting', 'surface_area_sqm', 'primary'),
    ('galvanizing', 'material_weight_kg', 'primary'),
    ('protective_packaging', 'package_count', 'primary'),
    ('protective_packaging', 'surface_area_sqm', 'secondary'),
    ('vehicle_loading', 'package_count', 'primary'),
    ('vehicle_loading', 'material_weight_kg', 'secondary'),
    ('delivery_trip', 'trip_count', 'primary'),
    ('manual_site_carry', 'package_count', 'primary'),
    ('manual_site_carry', 'floor_count', 'secondary'),
    ('site_protection', 'surface_area_sqm', 'primary'),
    ('cabinet_installation', 'cabinet_count', 'primary'),
    ('countertop_installation', 'object_count', 'primary'),
    ('countertop_installation', 'seam_length_lm', 'secondary'),
    ('metalwork_installation', 'object_count', 'primary'),
    ('glass_mirror_installation', 'material_area_sqm', 'primary'),
    ('site_anchoring', 'anchor_count', 'primary'),
    ('site_sealing', 'seam_length_lm', 'primary'),
    ('led_low_voltage_installation', 'led_length_lm', 'primary'),
    ('led_low_voltage_installation', 'electrical_point_count', 'secondary'),
    ('final_adjustment', 'hardware_count', 'primary'),
    ('site_cleanup', 'site_visit_count', 'primary')
) as mapping(operation_code, driver_code, driver_purpose)
join public.reference_operations o
    on o.operation_code = mapping.operation_code
on conflict (operation_id, driver_code) do update set
    driver_purpose = excluded.driver_purpose;
