[theme]
base = "light"
primaryColor = "#8049C6"
backgroundColor = "#F1EFEF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2A1F2C"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
